--- 
- hosts: all
  become: true
  gather_facts: yes
  ignore_errors: true
  vars_files:
    - variables.yml
  tasks:
    - name: Check the time
      command: datehh
#      when: ansible_distribution == "Ubuntu" or ansible_processor_nproc == 2
    - name: create user serge
      user:
        name: "{{user_name}}"
        comment: Serge Admin
    - name: create group
      group:
        name: "{{group_name}}"
        state: present
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present   